language: go

sudo: false
env:
    - GOARCH=amd64
    
go:
    - 1.6
    - 1.7
    - 1.8
    - tip

addons:
    apt: 
      packages: 
         - libsamplerate0
         - libsamplerate0-dev
before_install:
    - go get github.com/mattn/goveralls
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
