language: go

sudo: false
env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=386
    
go:
    - 1.7

addons:
    apt: 
      packages: 
         - libsamplerate0
         - libsamplerate0-dev
before_install:
    - go get github.com/mattn/goveralls
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - go test
